In [1]:
import pandas as pd
import numpy as np

osmDf = pd.read_csv('osm.csv', encoding='utf-8', delimiter=';')
osmDf.head()
osmDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 12 columns):
ID               792 non-null int64
LAT              792 non-null object
LON              792 non-null object
NAME             300 non-null object
TIMESTAMP        783 non-null object
ADDR_STREET      64 non-null object
ADDR_CITY        43 non-null object
ADDR_STATE       0 non-null float64
ADDR_POSTCODE    60 non-null object
TAG_KEY          783 non-null object
TAG_VALUE        779 non-null object
DISTANCE         783 non-null float64
dtypes: float64(2), int64(1), object(9)
memory usage: 74.3+ KB

In [2]:
osmDf.head()

,ID,LAT,LON,NAME,TIMESTAMP,ADDR_STREET,ADDR_CITY,ADDR_STATE,ADDR_POSTCODE,TAG_KEY,TAG_VALUE,DISTANCE
0,1229196667,"50,0902909","14,4494304",NaN,"36:12,0",NaN,NaN,NaN,NaN,AMENITY,recycling,573.0
1,1237556564,"50,0955973","14,4684661",Studio Divadla Kámen,"44:42,0",Nekvasilova,Praha 8,NaN,18600,AMENITY,theatre,966.0
2,1314084713,"50,0875412","14,4548586",MATRIX club,"19:59,0",Koněvova,Praha 3,NaN,NaN,AMENITY,nightclub,701.0
3,1317088234,"50,0935184","14,455158",Můj šálek kávy,"57:24,0",Koněvova,Praha,NaN,18600,AMENITY,cafe,36.0
4,1117933116,"50,0922297","14,4426762",Pizzeria Rialto,"02:22,0",NaN,NaN,NaN,NaN,AMENITY,restaurant,916.0

In [3]:
osmDf["LAT"] = osmDf["LAT"].replace(',','.', regex=True).astype(np.float)

osmDf.head()

,ID,LAT,LON,NAME,TIMESTAMP,ADDR_STREET,ADDR_CITY,ADDR_STATE,ADDR_POSTCODE,TAG_KEY,TAG_VALUE,DISTANCE
0,1229196667,50.090291,"14,4494304",NaN,"36:12,0",NaN,NaN,NaN,NaN,AMENITY,recycling,573.0
1,1237556564,50.095597,"14,4684661",Studio Divadla Kámen,"44:42,0",Nekvasilova,Praha 8,NaN,18600,AMENITY,theatre,966.0
2,1314084713,50.087541,"14,4548586",MATRIX club,"19:59,0",Koněvova,Praha 3,NaN,NaN,AMENITY,nightclub,701.0
3,1317088234,50.093518,"14,455158",Můj šálek kávy,"57:24,0",Koněvova,Praha,NaN,18600,AMENITY,cafe,36.0
4,1117933116,50.092230,"14,4426762",Pizzeria Rialto,"02:22,0",NaN,NaN,NaN,NaN,AMENITY,restaurant,916.0

In [4]:
osmDf["LON"] = osmDf["LON"].replace(',','.', regex=True).astype(np.float)

In [5]:
osmDf.head()

,ID,LAT,LON,NAME,TIMESTAMP,ADDR_STREET,ADDR_CITY,ADDR_STATE,ADDR_POSTCODE,TAG_KEY,TAG_VALUE,DISTANCE
0,1229196667,50.090291,14.449430,NaN,"36:12,0",NaN,NaN,NaN,NaN,AMENITY,recycling,573.0
1,1237556564,50.095597,14.468466,Studio Divadla Kámen,"44:42,0",Nekvasilova,Praha 8,NaN,18600,AMENITY,theatre,966.0
2,1314084713,50.087541,14.454859,MATRIX club,"19:59,0",Koněvova,Praha 3,NaN,NaN,AMENITY,nightclub,701.0
3,1317088234,50.093518,14.455158,Můj šálek kávy,"57:24,0",Koněvova,Praha,NaN,18600,AMENITY,cafe,36.0
4,1117933116,50.092230,14.442676,Pizzeria Rialto,"02:22,0",NaN,NaN,NaN,NaN,AMENITY,restaurant,916.0

In [6]:
osmDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 12 columns):
ID               792 non-null int64
LAT              792 non-null float64
LON              792 non-null float64
NAME             300 non-null object
TIMESTAMP        783 non-null object
ADDR_STREET      64 non-null object
ADDR_CITY        43 non-null object
ADDR_STATE       0 non-null float64
ADDR_POSTCODE    60 non-null object
TAG_KEY          783 non-null object
TAG_VALUE        779 non-null object
DISTANCE         783 non-null float64
dtypes: float64(4), int64(1), object(7)
memory usage: 74.3+ KB

In [7]:
osmDf.isnull().sum()

ID                 0
LAT                0
LON                0
NAME             492
TIMESTAMP          9
ADDR_STREET      728
ADDR_CITY        749
ADDR_STATE       792
ADDR_POSTCODE    732
TAG_KEY            9
TAG_VALUE         13
DISTANCE           9
dtype: int64

In [8]:
osmDf.fillna('Nezadané').head(3)

,ID,LAT,LON,NAME,TIMESTAMP,ADDR_STREET,ADDR_CITY,ADDR_STATE,ADDR_POSTCODE,TAG_KEY,TAG_VALUE,DISTANCE
0,1229196667,50.090291,14.449430,Nezadané,"36:12,0",Nezadané,Nezadané,Nezadané,Nezadané,AMENITY,recycling,573
1,1237556564,50.095597,14.468466,Studio Divadla Kámen,"44:42,0",Nekvasilova,Praha 8,Nezadané,18600,AMENITY,theatre,966
2,1314084713,50.087541,14.454859,MATRIX club,"19:59,0",Koněvova,Praha 3,Nezadané,Nezadané,AMENITY,nightclub,701

In [9]:
osmDf.groupby('NAME').count() # zjisteni poctu lokalit - 266

,ID,LAT,LON,TIMESTAMP,ADDR_STREET,ADDR_CITY,ADDR_STATE,ADDR_POSTCODE,TAG_KEY,TAG_VALUE,DISTANCE
NAME,,,,,,,,,,,
1. KáPA,1,1,1,1,0,0,0,0,1,1,1
Alabama,1,1,1,1,0,0,0,0,1,1,1
Albert,2,2,2,2,0,0,0,0,2,2,2
Alien Music bar,1,1,1,1,1,1,0,1,1,1,1
Alkohol a cigarety,1,1,1,1,0,0,0,0,1,1,1
Alza.cz,1,1,1,1,0,0,0,0,1,1,1
Amfora,1,1,1,1,0,0,0,0,1,1,1
Aron,1,1,1,1,0,0,0,0,1,1,1
Asijské bistro Tuan Vu Minh,1,1,1,1,0,0,0,0,1,1,1
B&B Prague-City Hotel,1,1,1,1,0,0,0,0,1,1,1
Bageterie,1,1,1,1,0,0,0,0,1,1,1
Bageterie Boulevard,1,1,1,1,1,1,0,1,1,1,1
Bajkazyl,2,2,2,2,2,2,0,2,2,2,2
Bar 109,1,1,1,1,0,0,0,0,1,1,1
Bar Club K35A,1,1,1,1,1,0,0,0,1,1,1
Billa,1,1,1,1,0,0,0,0,1,1,1
Bily Lev,1,1,1,1,0,0,0,0,1,1,1
Bistro Proti proudu,1,1,1,1,0,0,0,0,1,1,1
Blind Eye Hostel,1,1,1,1,0,0,0,0,1,1,1
CEEL,1,1,1,1,0,0,0,0,1,1,1
Cafe Bar Roka,1,1,1,1,0,0,0,0,1,1,1
Cafe Bar Vítkov,1,1,1,1,0,0,0,0,1,1,1
Cafe Sonia,1,1,1,1,0,0,0,0,1,1,1
Cafeteria & Pizzeria PERSONA,1,1,1,1,0,0,0,0,1,1,1
Café Element,1,1,1,1,1,1,0,1,1,1,1
Charleston,1,1,1,1,1,0,0,1,1,1,1
Chinese,1,1,1,1,1,0,0,1,1,1,1
Columbo,1,1,1,1,0,0,0,0,1,1,1
Country Life,1,1,1,1,1,1,0,1,1,1,1
CykloPrag,1,1,1,1,0,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
U České chalupy,1,1,1,1,0,0,0,0,1,1,1
UniCredit Bank,1,1,1,1,0,0,0,0,1,1,1
Urxova,2,2,2,2,0,0,0,0,2,2,2
V Roháčové,1,1,1,1,0,0,0,0,1,1,1
Vegan City,1,1,1,1,1,1,0,1,1,1,1
Večerka,2,2,2,2,0,0,0,0,2,2,2
Veřejné WC,2,2,2,2,0,0,0,0,2,2,2
Victor,1,1,1,1,0,0,0,0,1,1,1
Vinná club U Dolejáká,1,1,1,1,0,0,0,0,1,1,1
Vino Portugal,1,1,1,1,1,0,0,1,1,1,1
Vinotéka Karlín,1,1,1,1,0,0,0,0,1,1,1
Vinárna Křiáík,1,1,1,1,0,0,0,0,1,1,1
Vinárna Veltlín,1,1,1,1,1,1,0,1,1,1,1
Vojenský historický ústav Praha,1,1,1,1,1,0,0,1,1,1,1
XT3,1,1,1,1,0,0,0,0,1,1,1
Yang zi jiang,1,1,1,1,0,0,0,0,1,1,1
Zahrádky Žižkov,1,1,1,1,0,0,0,0,1,1,1
mamacoffee,1,1,1,1,0,0,0,0,1,1,1
minimarket,1,1,1,1,0,0,0,0,1,1,1
u Prokopa,1,1,1,1,0,0,0,0,1,1,1
á+á Auto,1,1,1,1,0,0,0,0,1,1,1
ČSOB,1,1,1,1,0,0,0,0,1,1,1
Černá kočka,1,1,1,1,0,0,0,0,1,1,1
Černínova,2,2,2,2,0,0,0,0,2,2,2
Česká podnikatelská pojištovna,2,2,2,2,0,0,0,0,2,2,2
Česká spořitelna,1,1,1,1,0,0,0,0,1,1,1
Čínské bistro,1,1,1,1,0,0,0,0,1,1,1
Šotek,1,1,1,1,0,0,0,0,1,1,1
Žabka,1,1,1,1,0,0,0,0,1,1,1
Železářství U Rotta,1,1,1,1,0,0,0,0,1,1,1

In [10]:
osmDf.groupby('ID').count() #764 ID z 792 řádků - nějaké duplicity

,LAT,LON,NAME,TIMESTAMP,ADDR_STREET,ADDR_CITY,ADDR_STATE,ADDR_POSTCODE,TAG_KEY,TAG_VALUE,DISTANCE
ID,,,,,,,,,,,
21311310,1,1,0,1,0,0,0,0,1,1,1
21311321,1,1,0,1,0,0,0,0,1,1,1
21673262,1,1,0,1,0,0,0,0,1,1,1
21673267,1,1,0,1,0,0,0,0,1,1,1
21673271,1,1,0,1,0,0,0,0,1,1,1
21673404,1,1,0,1,0,0,0,0,1,1,1
24569272,1,1,1,0,0,0,0,0,0,0,0
24569287,1,1,1,0,0,0,0,0,0,0,0
24569342,1,1,1,0,0,0,0,0,0,0,0
24958997,1,1,0,1,0,0,0,0,1,1,1
25662315,1,1,0,1,0,0,0,0,1,1,1
25662760,1,1,0,1,0,0,0,0,1,1,1
26422688,1,1,0,1,0,0,0,0,1,1,1
29381141,1,1,0,1,0,0,0,0,1,1,1
29581461,2,2,2,2,0,0,0,0,2,2,2
165899218,1,1,0,1,0,0,0,0,1,1,1
170269221,1,1,0,1,0,0,0,0,1,1,1
244015095,1,1,0,1,0,0,0,0,1,1,1
246535561,1,1,0,1,0,0,0,0,1,1,1
264838977,1,1,0,1,0,0,0,0,1,1,1
264838978,1,1,0,1,0,0,0,0,1,1,1
282546210,1,1,1,1,0,0,0,0,1,1,1
282546212,1,1,1,1,0,0,0,0,1,1,1
282546213,1,1,1,1,0,0,0,0,1,1,1
291562418,1,1,1,1,0,0,0,0,1,1,1
292456771,1,1,0,1,0,0,0,0,1,1,1
292456795,1,1,0,1,0,0,0,0,1,1,1
293572105,1,1,1,1,0,0,0,0,1,1,1
293572387,2,2,2,2,0,0,0,0,2,2,2
296478500,1,1,0,1,1,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
3814615427,1,1,1,1,0,0,0,0,1,1,1
3815608981,1,1,1,1,0,0,0,0,1,1,1
3815962567,1,1,1,1,0,0,0,0,1,1,1
3838733613,1,1,1,1,0,0,0,0,1,1,1
3909605659,1,1,0,1,0,0,0,0,1,1,1
3909610059,1,1,0,1,0,0,0,0,1,1,1
3909612350,1,1,0,1,0,0,0,0,1,1,1
3923581532,1,1,1,1,1,1,0,1,1,1,1
3936679460,1,1,1,1,1,1,0,1,1,1,1
3945402575,1,1,0,1,0,0,0,0,1,1,1
3986180425,1,1,0,1,0,0,0,0,1,1,1
3999437159,1,1,0,1,0,0,0,0,1,1,1
3999437160,1,1,0,1,0,0,0,0,1,1,1
4002541608,1,1,1,1,1,1,0,1,1,0,1
4017204046,1,1,1,1,0,0,0,0,1,1,1
4031606646,1,1,1,1,1,1,0,1,1,1,1
4033211984,1,1,1,1,0,0,0,0,1,1,1
4033212812,1,1,0,1,0,0,0,0,1,1,1
4033214990,1,1,0,1,0,0,0,0,1,1,1
4120903720,1,1,0,1,0,0,0,0,1,1,1
4120907377,1,1,0,1,0,0,0,0,1,1,1
4122993066,1,1,0,1,0,0,0,0,1,1,1
4123715590,1,1,1,1,0,0,0,0,1,1,1
4125046126,1,1,0,1,0,0,0,0,1,1,1
4142343080,1,1,0,1,0,0,0,0,1,1,1
4142343507,1,1,0,1,0,0,0,0,1,1,1
4142343508,1,1,0,1,0,0,0,0,1,1,1
4142343509,1,1,0,1,0,0,0,0,1,1,1
4142343511,1,1,0,1,0,0,0,0,1,1,1
4142343526,1,1,0,1,0,0,0,0,1,1,1

In [11]:
osmDf.groupby('NAME').ID.describe() 
#zgrupováno podle místa: 266 míst

,count,mean,std,min,25%,50%,75%,max
NAME,,,,,,,,
1. KáPA,1.0,1.236483e+09,NaN,1.236483e+09,1.236483e+09,1.236483e+09,1.236483e+09,1.236483e+09
Alabama,1.0,4.679642e+08,NaN,4.679642e+08,4.679642e+08,4.679642e+08,4.679642e+08,4.679642e+08
Albert,2.0,1.317603e+09,1.335321e+09,3.733884e+08,8.454955e+08,1.317603e+09,1.789710e+09,2.261817e+09
Alien Music bar,1.0,3.082106e+09,NaN,3.082106e+09,3.082106e+09,3.082106e+09,3.082106e+09,3.082106e+09
Alkohol a cigarety,1.0,3.276685e+09,NaN,3.276685e+09,3.276685e+09,3.276685e+09,3.276685e+09,3.276685e+09
Alza.cz,1.0,2.915624e+08,NaN,2.915624e+08,2.915624e+08,2.915624e+08,2.915624e+08,2.915624e+08
Amfora,1.0,3.682443e+08,NaN,3.682443e+08,3.682443e+08,3.682443e+08,3.682443e+08,3.682443e+08
Aron,1.0,1.487327e+09,NaN,1.487327e+09,1.487327e+09,1.487327e+09,1.487327e+09,1.487327e+09
Asijské bistro Tuan Vu Minh,1.0,3.838734e+09,NaN,3.838734e+09,3.838734e+09,3.838734e+09,3.838734e+09,3.838734e+09
B&B Prague-City Hotel,1.0,2.532190e+09,NaN,2.532190e+09,2.532190e+09,2.532190e+09,2.532190e+09,2.532190e+09
Bageterie,1.0,3.740677e+09,NaN,3.740677e+09,3.740677e+09,3.740677e+09,3.740677e+09,3.740677e+09
Bageterie Boulevard,1.0,3.154112e+09,NaN,3.154112e+09,3.154112e+09,3.154112e+09,3.154112e+09,3.154112e+09
Bajkazyl,2.0,2.796265e+09,7.071068e-01,2.796265e+09,2.796265e+09,2.796265e+09,2.796265e+09,2.796265e+09
Bar 109,1.0,4.678463e+08,NaN,4.678463e+08,4.678463e+08,4.678463e+08,4.678463e+08,4.678463e+08
Bar Club K35A,1.0,4.261620e+08,NaN,4.261620e+08,4.261620e+08,4.261620e+08,4.261620e+08,4.261620e+08
Billa,1.0,7.945366e+08,NaN,7.945366e+08,7.945366e+08,7.945366e+08,7.945366e+08,7.945366e+08
Bily Lev,1.0,3.557794e+09,NaN,3.557794e+09,3.557794e+09,3.557794e+09,3.557794e+09,3.557794e+09
Bistro Proti proudu,1.0,2.261945e+09,NaN,2.261945e+09,2.261945e+09,2.261945e+09,2.261945e+09,2.261945e+09
Blind Eye Hostel,1.0,3.316238e+09,NaN,3.316238e+09,3.316238e+09,3.316238e+09,3.316238e+09,3.316238e+09
CEEL,1.0,3.188225e+09,NaN,3.188225e+09,3.188225e+09,3.188225e+09,3.188225e+09,3.188225e+09
Cafe Bar Roka,1.0,3.229527e+09,NaN,3.229527e+09,3.229527e+09,3.229527e+09,3.229527e+09,3.229527e+09
Cafe Bar Vítkov,1.0,5.751733e+08,NaN,5.751733e+08,5.751733e+08,5.751733e+08,5.751733e+08,5.751733e+08
Cafe Sonia,1.0,3.726653e+09,NaN,3.726653e+09,3.726653e+09,3.726653e+09,3.726653e+09,3.726653e+09
Cafeteria & Pizzeria PERSONA,1.0,2.408660e+09,NaN,2.408660e+09,2.408660e+09,2.408660e+09,2.408660e+09,2.408660e+09
Café Element,1.0,3.364070e+09,NaN,3.364070e+09,3.364070e+09,3.364070e+09,3.364070e+09,3.364070e+09
Charleston,1.0,2.967412e+08,NaN,2.967412e+08,2.967412e+08,2.967412e+08,2.967412e+08,2.967412e+08
Chinese,1.0,2.967258e+08,NaN,2.967258e+08,2.967258e+08,2.967258e+08,2.967258e+08,2.967258e+08
Columbo,1.0,3.740688e+09,NaN,3.740688e+09,3.740688e+09,3.740688e+09,3.740688e+09,3.740688e+09
Country Life,1.0,2.869809e+09,NaN,2.869809e+09,2.869809e+09,2.869809e+09,2.869809e+09,2.869809e+09
CykloPrag,1.0,1.682876e+09,NaN,1.682876e+09,1.682876e+09,1.682876e+09,1.682876e+09,1.682876e+09
...,...,...,...,...,...,...,...,...
U České chalupy,1.0,3.071951e+08,NaN,3.071951e+08,3.071951e+08,3.071951e+08,3.071951e+08,3.071951e+08
UniCredit Bank,1.0,5.245157e+08,NaN,5.245157e+08,5.245157e+08,5.245157e+08,5.245157e+08,5.245157e+08
Urxova,2.0,3.861743e+08,0.000000e+00,3.861743e+08,3.861743e+08,3.861743e+08,3.861743e+08,3.861743e+08
V Roháčové,1.0,4.678463e+08,NaN,4.678463e+08,4.678463e+08,4.678463e+08,4.678463e+08,4.678463e+08
Vegan City,1.0,2.966087e+08,NaN,2.966087e+08,2.966087e+08,2.966087e+08,2.966087e+08,2.966087e+08
Večerka,2.0,2.261836e+09,4.242641e+00,2.261836e+09,2.261836e+09,2.261836e+09,2.261836e+09,2.261836e+09
Veřejné WC,2.0,6.191704e+08,1.697056e+01,6.191704e+08,6.191704e+08,6.191704e+08,6.191704e+08,6.191704e+08
Victor,1.0,3.546924e+08,NaN,3.546924e+08,3.546924e+08,3.546924e+08,3.546924e+08,3.546924e+08
Vinná club U Dolejáká,1.0,3.642977e+09,NaN,3.642977e+09,3.642977e+09,3.642977e+09,3.642977e+09,3.642977e+09
Vino Portugal,1.0,2.192325e+09,NaN,2.192325e+09,2.192325e+09,2.192325e+09,2.192325e+09,2.192325e+09
Vinotéka Karlín,1.0,3.731380e+09,NaN,3.731380e+09,3.731380e+09,3.731380e+09,3.731380e+09,3.731380e+09
Vinárna Křiáík,1.0,1.682874e+09,NaN,1.682874e+09,1.682874e+09,1.682874e+09,1.682874e+09,1.682874e+09
Vinárna Veltlín,1.0,2.441470e+09,NaN,2.441470e+09,2.441470e+09,2.441470e+09,2.441470e+09,2.441470e+09
Vojenský historický ústav Praha,1.0,2.966937e+08,NaN,2.966937e+08,2.966937e+08,2.966937e+08,2.966937e+08,2.966937e+08
XT3,1.0,4.505663e+08,NaN,4.505663e+08,4.505663e+08,4.505663e+08,4.505663e+08,4.505663e+08
Yang zi jiang,1.0,4.679642e+08,NaN,4.679642e+08,4.679642e+08,4.679642e+08,4.679642e+08,4.679642e+08
Zahrádky Žižkov,1.0,1.937948e+09,NaN,1.937948e+09,1.937948e+09,1.937948e+09,1.937948e+09,1.937948e+09
mamacoffee,1.0,3.598845e+09,NaN,3.598845e+09,3.598845e+09,3.598845e+09,3.598845e+09,3.598845e+09
minimarket,1.0,3.740656e+09,NaN,3.740656e+09,3.740656e+09,3.740656e+09,3.740656e+09,3.740656e+09
u Prokopa,1.0,3.740673e+09,NaN,3.740673e+09,3.740673e+09,3.740673e+09,3.740673e+09,3.740673e+09
á+á Auto,1.0,1.258710e+09,NaN,1.258710e+09,1.258710e+09,1.258710e+09,1.258710e+09,1.258710e+09
ČSOB,1.0,3.740677e+09,NaN,3.740677e+09,3.740677e+09,3.740677e+09,3.740677e+09,3.740677e+09
Černá kočka,1.0,3.067000e+08,NaN,3.067000e+08,3.067000e+08,3.067000e+08,3.067000e+08,3.067000e+08
Černínova,2.0,2.949139e+08,1.749061e+07,2.825462e+08,2.887301e+08,2.949139e+08,3.010978e+08,3.072817e+08
Česká podnikatelská pojištovna,2.0,2.610452e+09,0.000000e+00,2.610452e+09,2.610452e+09,2.610452e+09,2.610452e+09,2.610452e+09
Česká spořitelna,1.0,3.546931e+08,NaN,3.546931e+08,3.546931e+08,3.546931e+08,3.546931e+08,3.546931e+08
Čínské bistro,1.0,2.261836e+09,NaN,2.261836e+09,2.261836e+09,2.261836e+09,2.261836e+09,2.261836e+09
Šotek,1.0,2.080322e+09,NaN,2.080322e+09,2.080322e+09,2.080322e+09,2.080322e+09,2.080322e+09
Žabka,1.0,3.229527e+09,NaN,3.229527e+09,3.229527e+09,3.229527e+09,3.229527e+09,3.229527e+09
Železářství U Rotta,1.0,2.651971e+09,NaN,2.651971e+09,2.651971e+09,2.651971e+09,2.651971e+09,2.651971e+09

In [12]:
osmDf["NAME"][osmDf["NAME"] != ''].count() #počet záznamů bez udání místa

#vypiš jen záznamy s udáním místa - pak vypsat místo, GPS pozici, ID, adress, tag key a value
osm_uprava = osmDf[['NAME', 'ID', 'LAT', 'LON', 'TAG_KEY', 'TAG_VALUE', 'ADDR_STREET']][osmDf.NAME != '']

In [13]:
osm_uprava.head()

,NAME,ID,LAT,LON,TAG_KEY,TAG_VALUE,ADDR_STREET
0,NaN,1229196667,50.090291,14.449430,AMENITY,recycling,NaN
1,Studio Divadla Kámen,1237556564,50.095597,14.468466,AMENITY,theatre,Nekvasilova
2,MATRIX club,1314084713,50.087541,14.454859,AMENITY,nightclub,Koněvova
3,Můj šálek kávy,1317088234,50.093518,14.455158,AMENITY,cafe,Koněvova
4,Pizzeria Rialto,1117933116,50.092230,14.442676,AMENITY,restaurant,NaN

In [14]:
osm_uprava.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 792 entries, 0 to 791
Data columns (total 7 columns):
NAME           300 non-null object
ID             792 non-null int64
LAT            792 non-null float64
LON            792 non-null float64
TAG_KEY        783 non-null object
TAG_VALUE      779 non-null object
ADDR_STREET    64 non-null object
dtypes: float64(2), int64(1), object(4)
memory usage: 49.5+ KB

In [15]:
osm_uprava.tail()

,NAME,ID,LAT,LON,TAG_KEY,TAG_VALUE,ADDR_STREET
787,Eliška,2691013552,50.100045,14.445842,SHOP,confectionery,NaN
788,Ehrlich,307220746,50.089369,14.463043,TOURISM,hotel,NaN
789,GreenYacht Hotel,742443865,50.102100,14.459990,TOURISM,hotel,U Libeňského mostu
790,Meteor,296838175,50.094110,14.452415,UNCATEGORIZED,NaN,Sokolovská
791,Karlín,297896692,50.092409,14.458422,UNCATEGORIZED,NaN,NaN

In [16]:
osm_cisteDf = pd.DataFrame(osm_uprava)

In [17]:
osm_cisteDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 792 entries, 0 to 791
Data columns (total 7 columns):
NAME           300 non-null object
ID             792 non-null int64
LAT            792 non-null float64
LON            792 non-null float64
TAG_KEY        783 non-null object
TAG_VALUE      779 non-null object
ADDR_STREET    64 non-null object
dtypes: float64(2), int64(1), object(4)
memory usage: 49.5+ KB

In [18]:
osm_cisteDf[(osm_cisteDf["NAME"] != 'NaN')]

,NAME,ID,LAT,LON,TAG_KEY,TAG_VALUE,ADDR_STREET
0,NaN,1229196667,50.090291,14.449430,AMENITY,recycling,NaN
1,Studio Divadla Kámen,1237556564,50.095597,14.468466,AMENITY,theatre,Nekvasilova
2,MATRIX club,1314084713,50.087541,14.454859,AMENITY,nightclub,Koněvova
3,Můj šálek kávy,1317088234,50.093518,14.455158,AMENITY,cafe,Koněvova
4,Pizzeria Rialto,1117933116,50.092230,14.442676,AMENITY,restaurant,NaN
5,NaN,1229196569,50.093148,14.447992,AMENITY,recycling,NaN
6,NaN,1229196644,50.087441,14.453148,AMENITY,recycling,NaN
7,NaN,1252116706,50.085808,14.450650,AMENITY,school,NaN
8,Spirit Bar,1252116709,50.085946,14.448684,AMENITY,restaurant,NaN
9,NaN,1371440303,50.100808,14.449938,AMENITY,shelter,NaN
10,NaN,1239698662,50.090845,14.465198,AMENITY,drinking_water,NaN
11,Městská policie hlavního města Prahy,1252116711,50.085807,14.450582,AMENITY,police,NaN
12,NaN,1328266785,50.091173,14.445364,AMENITY,recycling,NaN
13,NaN,1229196627,50.095190,14.453693,AMENITY,recycling,NaN
14,NaN,1258717864,50.089884,14.461397,AMENITY,car_wash,NaN
15,NaN,1229196563,50.093970,14.451569,AMENITY,recycling,NaN
16,Dhaba Beas,1702407020,50.094404,14.452373,AMENITY,restaurant,NaN
17,Gate,1117933121,50.092182,14.442397,AMENITY,restaurant,NaN
18,NaN,3623046812,50.087813,14.456336,AMENITY,restaurant,NaN
19,NaN,3623057870,50.087951,14.455054,AMENITY,bench,NaN
20,U Karlínského přístavu,368244504,50.093483,14.448069,AMENITY,restaurant,NaN
21,Dobrá Karma,3726614863,50.084868,14.454765,AMENITY,restaurant,NaN
22,Amfora,368244318,50.093588,14.448627,AMENITY,restaurant,NaN
23,Cafe Sonia,3726652803,50.086544,14.452055,AMENITY,cafe,NaN
24,ČSOB,3740677346,50.092661,14.452410,AMENITY,bank,NaN
25,G a Hudební škola,3813119921,50.086302,14.457121,NaN,NaN,NaN
26,NaN,3909610059,50.093179,14.447216,AMENITY,bicycle_parking,NaN
27,Posta Praha 31,3623042982,50.087013,14.456323,AMENITY,post_office,NaN
28,NaN,3623046810,50.086610,14.455803,AMENITY,doctors,NaN
29,NaN,3623177569,50.087735,14.457035,AMENITY,restaurant,NaN
...,...,...,...,...,...,...,...
762,NaN,1494176982,50.086011,14.455548,AMENITY,recycling,NaN
763,CykloPrag,1682875960,50.099889,14.446103,SHOP,bicycle,NaN
764,Šotek,2080322483,50.091941,14.442372,SHOP,shoes,NaN
765,Albert,2261816986,50.092769,14.453019,SHOP,supermarket,NaN
766,RockOpera Praha,2291607737,50.099874,14.449815,AMENITY,theatre,Komunardá
767,MERCATO,2291607745,50.099374,14.445967,AMENITY,restaurant,NaN
768,á+á Auto,1258710282,50.089694,14.461382,SHOP,car_repair,NaN
769,NaN,2080322478,50.092437,14.443627,SHOP,stationery,NaN
770,Kolalevne,1838663299,50.086594,14.447297,SHOP,bicycle,NaN
771,NaN,2080322481,50.093758,14.451398,SHOP,hairdresser,NaN
772,Bajkazyl,2796265430,50.087773,14.452894,AMENITY,bar,Tachovské náměstí
773,NaN,2886693607,50.090929,14.465155,AMENITY,bicycle_parking,NaN
774,Pizzeria Vesuv,296678525,50.094576,14.455088,AMENITY,restaurant,Šaldova
775,Studna,296728279,50.095062,14.456738,AMENITY,restaurant,Sokolovská
776,NaN,1467045247,50.096699,14.461954,RAILWAY,crossing,NaN
777,NaN,1711518908,50.089985,14.451555,RAILWAY,buffer_stop,NaN
778,Karlínské náměstí,386174263,50.092753,14.445601,RAILWAY,tram_stop,NaN
779,Koněvova,386174281,50.094200,14.452122,RAILWAY,tram_stop,NaN
780,Fair&Bio obchádek,1241790358,50.091986,14.441608,SHOP,fairtrade,NaN
781,Večerka,2261835800,50.093722,14.455881,SHOP,convenience,NaN
782,Koberce K+K,2651970581,50.099345,14.447614,SHOP,furniture,NaN
783,Penny Market,2651970588,50.100364,14.446517,SHOP,supermarket,NaN
784,Železářství U Rotta,2651970589,50.099809,14.445460,SHOP,hardware,NaN
785,Bajkazyl,2796265431,50.087773,14.452894,SHOP,bicycle,Tachovské náměstí
786,SuperStarShop.cz (pouze výdej,2664820742,50.092161,14.444960,NaN,NaN,NaN
787,Eliška,2691013552,50.100045,14.445842,SHOP,confectionery,NaN
788,Ehrlich,307220746,50.089369,14.463043,TOURISM,hotel,NaN
789,GreenYacht Hotel,742443865,50.102100,14.459990,TOURISM,hotel,U Libeňského mostu
790,Meteor,296838175,50.094110,14.452415,UNCATEGORIZED,NaN,Sokolovská
791,Karlín,297896692,50.092409,14.458422,UNCATEGORIZED,NaN,NaN

In [19]:
osm_cisteDf[osm_cisteDf["NAME"] =='NaN'].shape

(0, 7)

In [20]:
osm_cisteDf.notnull().head()

    NAME    ID   LAT   LON  TAG_KEY  TAG_VALUE  ADDR_STREET
0  False  True  True  True     True       True        False
1   True  True  True  True     True       True         True
2   True  True  True  True     True       True         True
3   True  True  True  True     True       True         True
4   True  True  True  True     True       True        False

In [21]:
osm_cisteDf.NAME.dropna()

1                      Studio Divadla Kámen
2                               MATRIX club
3                            Můj šálek kávy
4                           Pizzeria Rialto
8                                Spirit Bar
11     Městská policie hlavního města Prahy
16                               Dhaba Beas
17                                     Gate
20                   U Karlínského přístavu
21                              Dobrá Karma
22                                   Amfora
23                               Cafe Sonia
24                                     ČSOB
25                        G a Hudební škola
27                           Posta Praha 31
32                                    Frida
33                            Lokál Hamburk
79                  Karel Havlíček Borovský
80                       Qarta architektura
81                     Monster Worldwide CZ
82                              Justiz-Caps
86           Česká podnikatelská pojištovna
90                                 Tusarova
92                              Park Vítkov
93                            Hotel Dalimil
94          Vojenský historický ústav Praha
96                            Hotel Seifert
97                                   Hostel
98                               Storm Club
99                                Puccelini
                       ...
731                               Rebellion
732                                    CEEL
735                                   Kebab
736                             Černá kočka
737                                 U Agamy
755                               Pernerova
763                               CykloPrag
764                                   Šotek
765                                  Albert
766                         RockOpera Praha
767                                 MERCATO
768                                á+á Auto
770                               Kolalevne
772                                Bajkazyl
774                          Pizzeria Vesuv
775                                  Studna
778                       Karlínské náměstí
779                                Koněvova
780                       Fair&Bio obchádek
781                                 Večerka
782                             Koberce K+K
783                            Penny Market
784                     Železářství U Rotta
785                                Bajkazyl
786           SuperStarShop.cz (pouze výdej
787                                  Eliška
788                                 Ehrlich
789                        GreenYacht Hotel
790                                  Meteor
791                                  Karlín
Name: NAME, Length: 300, dtype: object

In [22]:
osm_cisteDf.head()

,NAME,ID,LAT,LON,TAG_KEY,TAG_VALUE,ADDR_STREET
0,NaN,1229196667,50.090291,14.449430,AMENITY,recycling,NaN
1,Studio Divadla Kámen,1237556564,50.095597,14.468466,AMENITY,theatre,Nekvasilova
2,MATRIX club,1314084713,50.087541,14.454859,AMENITY,nightclub,Koněvova
3,Můj šálek kávy,1317088234,50.093518,14.455158,AMENITY,cafe,Koněvova
4,Pizzeria Rialto,1117933116,50.092230,14.442676,AMENITY,restaurant,NaN

In [23]:
osm_vycistenoDf=osm_cisteDf.fillna('Nezadane')

In [24]:
osm_vycistenoDf[osm_vycistenoDf["NAME"] == 'Nezadane'].shape

(492, 7)

In [25]:
osm_finalDf=osm_vycistenoDf[osm_vycistenoDf["NAME"] != 'Nezadane'] #je jich takto 300

In [26]:
osm_finalDf

,NAME,ID,LAT,LON,TAG_KEY,TAG_VALUE,ADDR_STREET
1,Studio Divadla Kámen,1237556564,50.095597,14.468466,AMENITY,theatre,Nekvasilova
2,MATRIX club,1314084713,50.087541,14.454859,AMENITY,nightclub,Koněvova
3,Můj šálek kávy,1317088234,50.093518,14.455158,AMENITY,cafe,Koněvova
4,Pizzeria Rialto,1117933116,50.092230,14.442676,AMENITY,restaurant,Nezadane
8,Spirit Bar,1252116709,50.085946,14.448684,AMENITY,restaurant,Nezadane
11,Městská policie hlavního města Prahy,1252116711,50.085807,14.450582,AMENITY,police,Nezadane
16,Dhaba Beas,1702407020,50.094404,14.452373,AMENITY,restaurant,Nezadane
17,Gate,1117933121,50.092182,14.442397,AMENITY,restaurant,Nezadane
20,U Karlínského přístavu,368244504,50.093483,14.448069,AMENITY,restaurant,Nezadane
21,Dobrá Karma,3726614863,50.084868,14.454765,AMENITY,restaurant,Nezadane
22,Amfora,368244318,50.093588,14.448627,AMENITY,restaurant,Nezadane
23,Cafe Sonia,3726652803,50.086544,14.452055,AMENITY,cafe,Nezadane
24,ČSOB,3740677346,50.092661,14.452410,AMENITY,bank,Nezadane
25,G a Hudební škola,3813119921,50.086302,14.457121,Nezadane,Nezadane,Nezadane
27,Posta Praha 31,3623042982,50.087013,14.456323,AMENITY,post_office,Nezadane
32,Frida,3815608981,50.092042,14.446470,AMENITY,cafe,Nezadane
33,Lokál Hamburk,3936679460,50.093188,14.446778,AMENITY,restaurant,Sokolovská
79,Karel Havlíček Borovský,1964429100,50.085097,14.454265,HISTORIC,memorial,Nezadane
80,Qarta architektura,2318297306,50.091709,14.455969,OFFICE,architect,Pernerova
81,Monster Worldwide CZ,2861714484,50.094987,14.450530,Nezadane,Nezadane,Nezadane
82,Justiz-Caps,296718724,50.095073,14.453425,OFFICE,company,Pobřežní
86,Česká podnikatelská pojištovna,2610451756,50.093501,14.444408,OFFICE,insurance,Nezadane
90,Tusarova,29581461,50.100820,14.450068,RAILWAY,tram_stop,Nezadane
92,Park Vítkov,3509790191,50.088200,14.454678,TOURISM,information,Nezadane
93,Hotel Dalimil,3726617573,50.086772,14.452242,TOURISM,hotel,Prokopova
94,Vojenský historický ústav Praha,296693693,50.087663,14.445164,TOURISM,museum,U památníku
96,Hotel Seifert,3229526509,50.087215,14.454218,TOURISM,hotel,Nezadane
97,Hostel,3779868858,50.093914,14.448474,TOURISM,hostel,Pobřežní
98,Storm Club,3204037436,50.087594,14.453192,UNCATEGORIZED,Nezadane,Tachovské náměstí
99,Puccelini,1165450456,50.101776,14.452767,AMENITY,restaurant,Nezadane
...,...,...,...,...,...,...,...
731,Rebellion,3086627019,50.087527,14.464947,AMENITY,restaurant,Nezadane
732,CEEL,3188225065,50.087067,14.450325,AMENITY,bar,Nezadane
735,Kebab,2886705950,50.097244,14.465474,AMENITY,fast_food,Nezadane
736,Černá kočka,306700004,50.090677,14.453448,AMENITY,restaurant,Nezadane
737,U Agamy,3188225064,50.085193,14.453030,AMENITY,restaurant,Nezadane
755,Pernerova,3815962567,50.089927,14.443226,HIGHWAY,bus_stop,Nezadane
763,CykloPrag,1682875960,50.099889,14.446103,SHOP,bicycle,Nezadane
764,Šotek,2080322483,50.091941,14.442372,SHOP,shoes,Nezadane
765,Albert,2261816986,50.092769,14.453019,SHOP,supermarket,Nezadane
766,RockOpera Praha,2291607737,50.099874,14.449815,AMENITY,theatre,Komunardá
767,MERCATO,2291607745,50.099374,14.445967,AMENITY,restaurant,Nezadane
768,á+á Auto,1258710282,50.089694,14.461382,SHOP,car_repair,Nezadane
770,Kolalevne,1838663299,50.086594,14.447297,SHOP,bicycle,Nezadane
772,Bajkazyl,2796265430,50.087773,14.452894,AMENITY,bar,Tachovské náměstí
774,Pizzeria Vesuv,296678525,50.094576,14.455088,AMENITY,restaurant,Šaldova
775,Studna,296728279,50.095062,14.456738,AMENITY,restaurant,Sokolovská
778,Karlínské náměstí,386174263,50.092753,14.445601,RAILWAY,tram_stop,Nezadane
779,Koněvova,386174281,50.094200,14.452122,RAILWAY,tram_stop,Nezadane
780,Fair&Bio obchádek,1241790358,50.091986,14.441608,SHOP,fairtrade,Nezadane
781,Večerka,2261835800,50.093722,14.455881,SHOP,convenience,Nezadane
782,Koberce K+K,2651970581,50.099345,14.447614,SHOP,furniture,Nezadane
783,Penny Market,2651970588,50.100364,14.446517,SHOP,supermarket,Nezadane
784,Železářství U Rotta,2651970589,50.099809,14.445460,SHOP,hardware,Nezadane
785,Bajkazyl,2796265431,50.087773,14.452894,SHOP,bicycle,Tachovské náměstí
786,SuperStarShop.cz (pouze výdej,2664820742,50.092161,14.444960,Nezadane,Nezadane,Nezadane
787,Eliška,2691013552,50.100045,14.445842,SHOP,confectionery,Nezadane
788,Ehrlich,307220746,50.089369,14.463043,TOURISM,hotel,Nezadane
789,GreenYacht Hotel,742443865,50.102100,14.459990,TOURISM,hotel,U Libeňského mostu
790,Meteor,296838175,50.094110,14.452415,UNCATEGORIZED,Nezadane,Sokolovská
791,Karlín,297896692,50.092409,14.458422,UNCATEGORIZED,Nezadane,Nezadane

In [27]:
osm_finalDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 1 to 791
Data columns (total 7 columns):
NAME           300 non-null object
ID             300 non-null int64
LAT            300 non-null float64
LON            300 non-null float64
TAG_KEY        300 non-null object
TAG_VALUE      300 non-null object
ADDR_STREET    300 non-null object
dtypes: float64(2), int64(1), object(4)
memory usage: 18.8+ KB

In [28]:
osm_finalDf["NAME"].count()

300

In [29]:
osm_finalDf.groupby('NAME').count() #je tam 34 duplicit - co s tím?

                                 ID  LAT  LON  TAG_KEY  TAG_VALUE  ADDR_STREET
NAME
1. KáPA                           1    1    1        1          1            1
Alabama                           1    1    1        1          1            1
Albert                            2    2    2        2          2            2
Alien Music bar                   1    1    1        1          1            1
Alkohol a cigarety                1    1    1        1          1            1
Alza.cz                           1    1    1        1          1            1
Amfora                            1    1    1        1          1            1
Aron                              1    1    1        1          1            1
Asijské bistro Tuan Vu Minh       1    1    1        1          1            1
B&B Prague-City Hotel             1    1    1        1          1            1
Bageterie                         1    1    1        1          1            1
Bageterie Boulevard               1    1    1        1          1            1
Bajkazyl                          2    2    2        2          2            2
Bar 109                           1    1    1        1          1            1
Bar Club K35A                     1    1    1        1          1            1
Billa                             1    1    1        1          1            1
Bily Lev                          1    1    1        1          1            1
Bistro Proti proudu               1    1    1        1          1            1
Blind Eye Hostel                  1    1    1        1          1            1
CEEL                              1    1    1        1          1            1
Cafe Bar Roka                     1    1    1        1          1            1
Cafe Bar Vítkov                   1    1    1        1          1            1
Cafe Sonia                        1    1    1        1          1            1
Cafeteria & Pizzeria PERSONA      1    1    1        1          1            1
Café Element                      1    1    1        1          1            1
Charleston                        1    1    1        1          1            1
Chinese                           1    1    1        1          1            1
Columbo                           1    1    1        1          1            1
Country Life                      1    1    1        1          1            1
CykloPrag                         1    1    1        1          1            1
...                              ..  ...  ...      ...        ...          ...
U České chalupy                   1    1    1        1          1            1
UniCredit Bank                    1    1    1        1          1            1
Urxova                            2    2    2        2          2            2
V Roháčové                        1    1    1        1          1            1
Vegan City                        1    1    1        1          1            1
Večerka                           2    2    2        2          2            2
Veřejné WC                        2    2    2        2          2            2
Victor                            1    1    1        1          1            1
Vinná club U Dolejáká             1    1    1        1          1            1
Vino Portugal                     1    1    1        1          1            1
Vinotéka Karlín                   1    1    1        1          1            1
Vinárna Křiáík                    1    1    1        1          1            1
Vinárna Veltlín                   1    1    1        1          1            1
Vojenský historický ústav Praha   1    1    1        1          1            1
XT3                               1    1    1        1          1            1
Yang zi jiang                     1    1    1        1          1            1
Zahrádky Žižkov                   1    1    1        1          1            1
mamacoffee                        1    1    1        1          1            1
minimarket                        1    1    1        1          1            1
u Prokopa                         1    1    1        1          1            1
á+á Auto                          1    1    1        1          1            1
ČSOB                              1    1    1        1          1            1
Černá kočka                       1    1    1        1          1            1
Černínova                         2    2    2        2          2            2
Česká podnikatelská pojištovna    2    2    2        2          2            2
Česká spořitelna                  1    1    1        1          1            1
Čínské bistro                     1    1    1        1          1            1
Šotek                             1    1    1        1          1            1
Žabka                             1    1    1        1          1            1
Železářství U Rotta               1    1    1        1          1            1

[266 rows x 6 columns]

In [30]:
osm_finalDf1=osm_finalDf.drop_duplicates("NAME", keep='first', inplace=False)

osm_finalDf1.head()

osm_finalDf1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266 entries, 1 to 791
Data columns (total 7 columns):
NAME           266 non-null object
ID             266 non-null int64
LAT            266 non-null float64
LON            266 non-null float64
TAG_KEY        266 non-null object
TAG_VALUE      266 non-null object
ADDR_STREET    266 non-null object
dtypes: float64(2), int64(1), object(4)
memory usage: 16.6+ KB

In [31]:
osm_finalDf1.groupby('NAME').count()

                                 ID  LAT  LON  TAG_KEY  TAG_VALUE  ADDR_STREET
NAME
1. KáPA                           1    1    1        1          1            1
Alabama                           1    1    1        1          1            1
Albert                            1    1    1        1          1            1
Alien Music bar                   1    1    1        1          1            1
Alkohol a cigarety                1    1    1        1          1            1
Alza.cz                           1    1    1        1          1            1
Amfora                            1    1    1        1          1            1
Aron                              1    1    1        1          1            1
Asijské bistro Tuan Vu Minh       1    1    1        1          1            1
B&B Prague-City Hotel             1    1    1        1          1            1
Bageterie                         1    1    1        1          1            1
Bageterie Boulevard               1    1    1        1          1            1
Bajkazyl                          1    1    1        1          1            1
Bar 109                           1    1    1        1          1            1
Bar Club K35A                     1    1    1        1          1            1
Billa                             1    1    1        1          1            1
Bily Lev                          1    1    1        1          1            1
Bistro Proti proudu               1    1    1        1          1            1
Blind Eye Hostel                  1    1    1        1          1            1
CEEL                              1    1    1        1          1            1
Cafe Bar Roka                     1    1    1        1          1            1
Cafe Bar Vítkov                   1    1    1        1          1            1
Cafe Sonia                        1    1    1        1          1            1
Cafeteria & Pizzeria PERSONA      1    1    1        1          1            1
Café Element                      1    1    1        1          1            1
Charleston                        1    1    1        1          1            1
Chinese                           1    1    1        1          1            1
Columbo                           1    1    1        1          1            1
Country Life                      1    1    1        1          1            1
CykloPrag                         1    1    1        1          1            1
...                              ..  ...  ...      ...        ...          ...
U České chalupy                   1    1    1        1          1            1
UniCredit Bank                    1    1    1        1          1            1
Urxova                            1    1    1        1          1            1
V Roháčové                        1    1    1        1          1            1
Vegan City                        1    1    1        1          1            1
Večerka                           1    1    1        1          1            1
Veřejné WC                        1    1    1        1          1            1
Victor                            1    1    1        1          1            1
Vinná club U Dolejáká             1    1    1        1          1            1
Vino Portugal                     1    1    1        1          1            1
Vinotéka Karlín                   1    1    1        1          1            1
Vinárna Křiáík                    1    1    1        1          1            1
Vinárna Veltlín                   1    1    1        1          1            1
Vojenský historický ústav Praha   1    1    1        1          1            1
XT3                               1    1    1        1          1            1
Yang zi jiang                     1    1    1        1          1            1
Zahrádky Žižkov                   1    1    1        1          1            1
mamacoffee                        1    1    1        1          1            1
minimarket                        1    1    1        1          1            1
u Prokopa                         1    1    1        1          1            1
á+á Auto                          1    1    1        1          1            1
ČSOB                              1    1    1        1          1            1
Černá kočka                       1    1    1        1          1            1
Černínova                         1    1    1        1          1            1
Česká podnikatelská pojištovna    1    1    1        1          1            1
Česká spořitelna                  1    1    1        1          1            1
Čínské bistro                     1    1    1        1          1            1
Šotek                             1    1    1        1          1            1
Žabka                             1    1    1        1          1            1
Železářství U Rotta               1    1    1        1          1            1

[266 rows x 6 columns]

In [32]:
osm_finalDf1.groupby('TAG_KEY').count()

               NAME   ID  LAT  LON  TAG_VALUE  ADDR_STREET
TAG_KEY
AMENITY         132  132  132  132        132          132
BUILDING          1    1    1    1          1            1
HIGHWAY           6    6    6    6          6            6
HISTORIC          3    3    3    3          3            3
LEISURE           2    2    2    2          2            2
MAN_MADE         38   38   38   38         38           38
Nezadane          7    7    7    7          7            7
OFFICE            6    6    6    6          6            6
RAILWAY           3    3    3    3          3            3
SHOP             40   40   40   40         40           40
SPORT             2    2    2    2          2            2
TOURISM          22   22   22   22         22           22
UNCATEGORIZED     4    4    4    4          4            4

In [33]:
osm_finalDf1.to_csv('osm_final.csv', encoding='utf-8', index=False)